### ISSUE TITLE
Links to questions are not permanent

### ISSUE THREAD

**Issue by hgwood** [Zenika/FAQ#24]
Editing a question generates a new slug for the URL, so all links pointing to the question are then broken.

Example:
- I create a question "How to access the management console of a Google Cloud project?"
- The link to the question is "https://faq.zenika.com/#/q/how-to-access-the-management-console-of-a-google-cloud-project"
- I post the link to Workplace
- I edit the question to "How to access the management console of a Google Cloud project? Hello"
- The link becomes "https://faq.zenika.com/#/q/how-to-access-the-management-console-of-a-google-cloud-project-hello"
- The old link does not work anymore, so the link on Workplace is broken

**Comment by nlepage** [comment]
However having the title in the URL is nice.
A common solution is to add add the id of the linked resource at the end of the URL :
https://faq.zenika.com/#/q/how-to-access-the-management-console-of-a-google-cloud-project-hello-123456
This is used in many news web sites.

**Comment by Errorname** [comment]
So if I follow what you are saying, we should have a url like this: https://faq.zenika.com/#/q/my-title-123456

And I should only take the uid at the end of the url to fetch the ressource ? This way, whatever the title is, we still get the right ressource.

Should I add a redirection if the title is wrong ? /q/my-title-123456 => /q/my-new-title-123456
So that people doesn't try to share the old url.

**Comment by nlepage** [comment]
Yes that's what I meant.
A 301 redicrect is not crucial, but if it can be done easily it's a plus :+1:.
